version: '3.7'
services:
    app:
        build:
            context: .
        ports:
        - '8080:8080'
        volumes:
            - '.:/weblib:cached'
        command: /bin/sh -c "yarn serve"
    
